#Handling Categorical & Numerical Features

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer

In [7]:
df = pd.DataFrame({
    "Name"          : ['Sade', 'Bob', 'Charlie', 'Joan', 'Bose', 'Odogwu'],
    "gender"        : ['Female', 'Male', 'Male', 'Female', 'Female', 'Male'],
    "city"          : ['Lagos', 'Abuja', 'Ibadan', 'Lagos', 'Abuja', 'Ibadan'],
    "education"     : ['Graduate', 'Not Graduate', 'Graduate', 'Graduate', 'Not Graduate', 'Graduate'],
    "risk_level"    : ['Low', 'Medium', 'High', 'Low', 'High', 'Medium'],  
    "income"        : [55000, 32000, 78000, 91000, 46000, 63000],
    "loan_amount"   : [200000, 150000, 450000, 500000, 175000, 310000],
    "loan_approved" : [1, 0, 1, 1, 0, 1]
})
df

,Name,gender,city,education,risk_level,income,loan_amount,loan_approved
0,Sade,Female,Lagos,Graduate,Low,55000,200000,1
1,Bob,Male,Abuja,Not Graduate,Medium,32000,150000,0
2,Charlie,Male,Ibadan,Graduate,High,78000,450000,1
3,Joan,Female,Lagos,Graduate,Low,91000,500000,1
4,Bose,Female,Abuja,Not Graduate,High,46000,175000,0
5,Odogwu,Male,Ibadan,Graduate,Medium,63000,310000,1

In [8]:
dummies = pd.get_dummies(df['Name'], dtype=int)
dummies

   Bob  Bose  Charlie  Joan  Odogwu  Sade
0    0     0        0     0       0     1
1    1     0        0     0       0     0
2    0     0        1     0       0     0
3    0     0        0     1       0     0
4    0     1        0     0       0     0
5    0     0        0     0       1     0

In [9]:
merged = pd.concat([df, dummies],axis='columns')
merged

,Name,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,Sade,Female,Lagos,Graduate,Low,55000,200000,1,0,0,0,0,0,1
1,Bob,Male,Abuja,Not Graduate,Medium,32000,150000,0,1,0,0,0,0,0
2,Charlie,Male,Ibadan,Graduate,High,78000,450000,1,0,0,1,0,0,0
3,Joan,Female,Lagos,Graduate,Low,91000,500000,1,0,0,0,1,0,0
4,Bose,Female,Abuja,Not Graduate,High,46000,175000,0,0,1,0,0,0,0
5,Odogwu,Male,Ibadan,Graduate,Medium,63000,310000,1,0,0,0,0,1,0

In [10]:
new_df = merged.drop(['Name'], axis='columns')
new_df

,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,Female,Lagos,Graduate,Low,55000,200000,1,0,0,0,0,0,1
1,Male,Abuja,Not Graduate,Medium,32000,150000,0,1,0,0,0,0,0
2,Male,Ibadan,Graduate,High,78000,450000,1,0,0,1,0,0,0
3,Female,Lagos,Graduate,Low,91000,500000,1,0,0,0,1,0,0
4,Female,Abuja,Not Graduate,High,46000,175000,0,0,1,0,0,0,0
5,Male,Ibadan,Graduate,Medium,63000,310000,1,0,0,0,0,1,0

In [11]:
new_df["gender"]

0    Female
1      Male
2      Male
3    Female
4    Female
5      Male
Name: gender, dtype: object

In [13]:
label_encoder = LabelEncoder()

new_df["gender"] = label_encoder.fit_transform(new_df["gender"])

new_df

,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,0,Lagos,Graduate,Low,55000,200000,1,0,0,0,0,0,1
1,1,Abuja,Not Graduate,Medium,32000,150000,0,1,0,0,0,0,0
2,1,Ibadan,Graduate,High,78000,450000,1,0,0,1,0,0,0
3,0,Lagos,Graduate,Low,91000,500000,1,0,0,0,1,0,0
4,0,Abuja,Not Graduate,High,46000,175000,0,0,1,0,0,0,0
5,1,Ibadan,Graduate,Medium,63000,310000,1,0,0,0,0,1,0

In [18]:
new_df[["risk_level"]]
new_df

,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,0,Lagos,Graduate,Low,55000,200000,1,0,0,0,0,0,1
1,1,Abuja,Not Graduate,Medium,32000,150000,0,1,0,0,0,0,0
2,1,Ibadan,Graduate,High,78000,450000,1,0,0,1,0,0,0
3,0,Lagos,Graduate,Low,91000,500000,1,0,0,0,1,0,0
4,0,Abuja,Not Graduate,High,46000,175000,0,0,1,0,0,0,0
5,1,Ibadan,Graduate,Medium,63000,310000,1,0,0,0,0,1,0

In [21]:
ord_encoder = OrdinalEncoder()

new_df["risk_level"] = ord_encoder.fit_transform(new_df[["risk_level"]])
new_df

,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,0,Lagos,Graduate,1.0,55000,200000,1,0,0,0,0,0,1
1,1,Abuja,Not Graduate,2.0,32000,150000,0,1,0,0,0,0,0
2,1,Ibadan,Graduate,0.0,78000,450000,1,0,0,1,0,0,0
3,0,Lagos,Graduate,1.0,91000,500000,1,0,0,0,1,0,0
4,0,Abuja,Not Graduate,0.0,46000,175000,0,0,1,0,0,0,0
5,1,Ibadan,Graduate,2.0,63000,310000,1,0,0,0,0,1,0

In [22]:
df.head()

,Name,gender,city,education,risk_level,income,loan_amount,loan_approved
0,Sade,Female,Lagos,Graduate,Low,55000,200000,1
1,Bob,Male,Abuja,Not Graduate,Medium,32000,150000,0
2,Charlie,Male,Ibadan,Graduate,High,78000,450000,1
3,Joan,Female,Lagos,Graduate,Low,91000,500000,1
4,Bose,Female,Abuja,Not Graduate,High,46000,175000,0

In [23]:
ct = ColumnTransformer([('Name', OneHotEncoder(), [0])], remainder = 'passthrough')
ct_x = ct.fit_transform(df)
ct_x

array([[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 'Female', 'Lagos', 'Graduate',
        'Low', 55000, 200000, 1],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Male', 'Abuja', 'Not Graduate',
        'Medium', 32000, 150000, 0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 'Male', 'Ibadan', 'Graduate',
        'High', 78000, 450000, 1],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 'Female', 'Lagos', 'Graduate',
        'Low', 91000, 500000, 1],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 'Female', 'Abuja', 'Not Graduate',
        'High', 46000, 175000, 0],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 'Male', 'Ibadan', 'Graduate',
        'Medium', 63000, 310000, 1]], dtype=object)

In [24]:
ct_x[:,1:]

array([[0.0, 0.0, 0.0, 0.0, 1.0, 'Female', 'Lagos', 'Graduate', 'Low',
        55000, 200000, 1],
       [0.0, 0.0, 0.0, 0.0, 0.0, 'Male', 'Abuja', 'Not Graduate',
        'Medium', 32000, 150000, 0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 'Male', 'Ibadan', 'Graduate', 'High',
        78000, 450000, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 'Female', 'Lagos', 'Graduate', 'Low',
        91000, 500000, 1],
       [1.0, 0.0, 0.0, 0.0, 0.0, 'Female', 'Abuja', 'Not Graduate',
        'High', 46000, 175000, 0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 'Male', 'Ibadan', 'Graduate', 'Medium',
        63000, 310000, 1]], dtype=object)

STANDARDIZATION AND NORMALIZATION

In [29]:
# Normalization using MinMaxScaler
scaler = MinMaxScaler()
new_df[['loan_amount', 'loan_approved']] = scaler.fit_transform(new_df[['loan_amount', 'loan_approved']])
new_df

,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,0,Lagos,Graduate,1.0,55000,0.142857,1.0,0,0,0,0,0,1
1,1,Abuja,Not Graduate,2.0,32000,0.000000,0.0,1,0,0,0,0,0
2,1,Ibadan,Graduate,0.0,78000,0.857143,1.0,0,0,1,0,0,0
3,0,Lagos,Graduate,1.0,91000,1.000000,1.0,0,0,0,1,0,0
4,0,Abuja,Not Graduate,0.0,46000,0.071429,0.0,0,1,0,0,0,0
5,1,Ibadan,Graduate,2.0,63000,0.457143,1.0,0,0,0,0,1,0

In [31]:
# Standardization using StandardScaler
std_scaler = StandardScaler()
new_df[['loan_amount', 'loan_approved']] = std_scaler.fit_transform(new_df[['loan_amount', 'loan_approved']])
new_df

,gender,city,education,risk_level,income,loan_amount,loan_approved,Bob,Bose,Charlie,Joan,Odogwu,Sade
0,0,Lagos,Graduate,1.0,55000,-0.717845,0.707107,0,0,0,0,0,1
1,1,Abuja,Not Graduate,2.0,32000,-1.085971,-1.414214,1,0,0,0,0,0
2,1,Ibadan,Graduate,0.0,78000,1.122784,0.707107,0,0,1,0,0,0
3,0,Lagos,Graduate,1.0,91000,1.490910,0.707107,0,0,0,1,0,0
4,0,Abuja,Not Graduate,0.0,46000,-0.901908,-1.414214,0,1,0,0,0,0
5,1,Ibadan,Graduate,2.0,63000,0.092031,0.707107,0,0,0,0,1,0